platform :ios, '12.4'

target 'RNSDKSample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RNSDKSample
  pod 'RNSDK', :podspec => '../../ios/SDKOutput/RNSDK.podspec'
end
